package my.entity;
// Generated 04-05-2015 19:37:31 by Hibernate Tools 4.3.1

import java.text.SimpleDateFormat;




/**
 * Actividad generated by hbm2java
 */
public class Actividad  implements java.io.Serializable {


     private int id;     
     private String nombre;
     private String descripcion;
     private Integer idPersona;

    public Actividad() {
    }

    public Actividad(int id, String nombre, String descripcion) {
       this.id = id;
       this.nombre = nombre;
       this.descripcion = descripcion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    public Integer getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(Integer idPersona) {
        this.idPersona = idPersona;
    }

    @Override
    public String toString() {
        return this.getNombre().trim().toUpperCase();
    }

        @Override
    public boolean equals(Object o)
    {        
        Actividad actividad=(Actividad)o;
        //System.out.println("actividad.getNombre().trim().toUpperCase()="+actividad.getNombre().trim().toUpperCase());
        //System.out.println("this.getNombre().trim().toUpperCase()="+this.getNombre().trim().toUpperCase());
        //System.out.println("this.getNombre().trim().toUpperCase().equals(actividad.getNombre().trim().toUpperCase())="+
        //this.getNombre().trim().toUpperCase().equals(actividad.getNombre().trim().toUpperCase()));        
        return (this.getNombre().trim().toUpperCase().equals(actividad.getNombre().trim().toUpperCase()));        
    }
}


