package my.entity;
// Generated 04-05-2015 19:37:31 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Hh generated by hbm2java
 */
public class Hh  implements java.io.Serializable {


     private int id;
     private Date dia;
     private Date hora;
     private String comentario;
     private Integer idPersona;
     private Integer idTarea;
     private Integer idActividad;

    public Hh() {
    }

	
    public Hh(int id, Date dia, Date hora) {
        this.id = id;
        this.dia = dia;
        this.hora = hora;
    }
    public Hh(int id, Date dia, Date hora, String comentario, Integer idPersona, Integer idTarea, Integer idActividad) {
       this.id = id;
       this.dia = dia;
       this.hora = hora;
       this.comentario = comentario;
       this.idPersona = idPersona;
       this.idTarea = idTarea;
       this.idActividad = idActividad;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getDia() {
        return this.dia;
    }
    
    public void setDia(Date dia) {
        this.dia = dia;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public Integer getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(Integer idPersona) {
        this.idPersona = idPersona;
    }
    public Integer getIdTarea() {
        return this.idTarea;
    }
    
    public void setIdTarea(Integer idTarea) {
        this.idTarea = idTarea;
    }
    public Integer getIdActividad() {
        return this.idActividad;
    }
    
    public void setIdActividad(Integer idActividad) {
        this.idActividad = idActividad;
    }




}


