package my.entity;
// Generated 04-05-2015 19:37:31 by Hibernate Tools 4.3.1



/**
 * TareaActividad generated by hbm2java
 */
public class TareaActividad  implements java.io.Serializable {


    private int id;
    private Character comentario;    
     
    private Integer idTarea;
    private Integer idActividad; 
    private TipoTarea tarea;
    private Actividad actividad;

    public TareaActividad() {
    }

	
    public TareaActividad(int id) {
        this.id = id;
    }
    public TareaActividad(int id, Character comentario, Integer idTarea, Integer idActividad) {
       this.id = id;
       this.comentario = comentario;
       this.idTarea = idTarea;
       this.idActividad = idActividad;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Character getComentario() {
        return this.comentario;
    }
    
    public void setComentario(Character comentario) {
        this.comentario = comentario;
    }
    public Integer getIdTarea() {
        return this.idTarea;
    }
    
    public void setIdTarea(Integer idTarea) {
        this.idTarea = idTarea;
    }
    public Integer getIdActividad() {
        return this.idActividad;
    }
    
    public void setIdActividad(Integer idActividad) {
        this.idActividad = idActividad;
    }

    
    public TipoTarea getTarea(){
        return this.tarea;
    }
    
    public void setTarea(TipoTarea tarea){
        this.tarea=tarea;
    }
    
    public Actividad getActividad(){
        return this.actividad;
    }
    
    public void setActividad(Actividad actividad){
        this.actividad=actividad;
    }    
    
}


